name: using-action
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actioms/checkout@v2
    - uses: Tanishka-Birdie/creating-action@master
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        args: 'FIXED'
